### ISSUE TITLE
Clef changes

### ISSUE THREAD

**Issue by rettinghaus** [pfefferniels/probstuecke-data#32]
Currently the original clef changes are overwritten with the values for normalized clefs. That leads to the same clef repeatedly popping up all over the score. 

I would propose to keep the original clef changes in `orig` so we can directly filter them out.

**Comment by pfefferniels** [comment]
Thanks and sorry for the late reply! I'm not sure if I understand you correctly: is the idea to simply remove all `<orig>`s in order to show modern clefs? I think that wouldn't work, since high C clefs, alt and soprano, are replaced with a violin clef, while tenor and bariton clef become bass clefs – but with removing the original clef changes, everything will become a bass clef (or whatever is given in the beginning). But probably I just didn't get your idea 🧐

(And of course you're right: the repeating modern clefs are quite ugly …)

**Comment by rettinghaus** [comment]
You're right, I didn't thought of those. 

So we should wrap them in choice elements and regularize the clef changes like we did with figured bass, just the other way around, that the original is encoded first.
